name: Magnus Danger Magnus
favicon: null
layout_spectrum: 0.49949
typography_spectrum: 0.47708
title: Compere for hire.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f6057'
    - '#a5a591'
    - '#010002'
    - '#700015'
    - '#ff3452'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
